### ISSUE TITLE
developer experience checklist

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/node-sdk#224]
- [x] ~~make sure it scales, it could be in the front page of reddit~~ NA
   * Mainly looking at page weight: Shoot for 2-3mb max and rendering in 5 sec or less. 
   * Test with dev tools throttling to 3G speeds and make sure things are still reasonable. 
- [x] Add google analytics
- [x] blue-green deployment + travis (see [this](https://github.com/IBM-Bluemix/cf-deployment-tracker-service))
- [x] testing + travis (see [this](https://github.com/germanattanasio/jenkins-badges))
- [x] security.js (helmet + express-rate-limitation) + CSRF  (see personality-insights and speech demos)
- [x] `package.json` should not specify node-engine so that Bluemix will always use the latest one.
- [x] Google RE-Captcha support (make sure design take this into account when designing a demo)
   * Talk to design to add it for existing demos.
- [x] Update travis to send emails when there is a tag release.
- [x] [Bluemix deployment tracker](https://github.com/watson-developer-cloud/natural-language-classifier-nodejs/blob/master/server.js#L9) and [privacy notice](https://github.com/watson-developer-cloud/natural-language-classifier-nodejs/blob/master/README.md#privacy-notice)

**Comment by nfriedly** [comment]
Most of these don't really apply to an SDK, and the ones that do, such as testing + travis are already in place here. Closing.
