### ISSUE TITLE
v3 Goals

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/node-sdk#443]
Breaking changes:
- [x] Fix default URL for Language Translator #318
- [x] Change createRecognizeStream to match service defaults - #257 
- [x] Share as much code as possible between [watson-speech](https://github.com/watson-developer-cloud/speech-javascript-sdk) and this repo
  * Or, just combine them together into one
- [x] ~Make nearly all methods return a Promise instead of a stream~
  * For methods where returning a Stream makes sense, add the word "stream" to the name
  * For methods where either one may make sense, just have two methods
- [x] ~Consider switching to `fetch` to allow simpler code and smaller browser builds~
  * Also consider restructuring request template as part of this - could allow "generic" things to be 
added without having to send them to the constructor.
  * Consider using https://github.com/mikeal/r2 or https://www.npmjs.com/package/axios under-the-hood
- [x] Consider switching to ES6 modules
- [x] Consider automated code generation from Swagger JSON for majority of SDK. See
  * https://github.com/swagger-api/swagger-js
  * https://github.com/wcandillon/swagger-js-codegen
- [x] Consider changing "get multiple things" api methods to `listThings()` instead of `getThings()` to reduce confusion with `getThing()` methods for getting a single "thing". 
  * Will want to create aliases for backwards-compatibility

Non-breaking changes that may still make sense to include in v3
- [x] Move request logic and error formatting into a series of methods on the base class
  * Should allow for generally simpler code because "weird" things can be scoped to only their module - e.g. #478 
- [x] ES5 builds for compatibility with older systems - #423 
- [x] Make better use of various ES6 features (class, template strings, etc)
- [x] Pre-build browser bundles
  * Modern bundle that retains various ES6 features such as Class syntax and native Promises
  * Compatibility bundle that uses ES5 syntax and includes pollyfills
  * Both could skip modules that are known to not work from a browser context

Most of these should probably get their own ticket, but we can do that as we go. 

This is a pretty tall order, and v3 will likely ship without including everything here, especially the "Consider..." ones.
